config/routes.rb
MiniProject::Application.routes.draw do
  resources :blogs

  root 'blogs#index'

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:blog_id, :blog_title, :blog_detail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def nl2br(txt)
    return txt.gsub(/\n/,'<br />')
  end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.number_field :blog_id %>
  </div>
  <div class="field">
    <%= f.label :blog_title %><br>
    <%= f.text_field :blog_title %>
  </div>
  <div class="field">
    <%= f.label :blog_detail %><br>
    <%= f.text_area :blog_detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/_side_menu.html.erb
<div class="side-menu">
  <div id="archive">
    <ul>
      <li class="title">
        <i class="icon-tag icon-large"></i>
        <span>Archive</span>
      </li>
      <li>
        <i class="icon-chevron-right"></i>
        <a href="#">何とか何とか何とか何とかの日記</a>
      </li>
      <li>
        <i class="icon-chevron-right"></i>
        <a href="#">何とか何とか何とか何とかの日記</a>
      </li>
      <li>
        <i class="icon-chevron-right"></i>
        <a href="#">何とか何とか何とか何とかの日記</a>
      </li>
      <li>
        <i class="icon-chevron-right"></i>
        <a href="#">何とか何とか何とか何とかの日記</a>
      </li>
      <li>
        <i class="icon-chevron-right"></i>
        <a href="#">何とか何とか何とか何とかの日記</a>
      </li>
    </ul>
  </div><!-- /archive -->
  <div id="manage-menu">
    <ul>
      <li class="title">
        <i class="icon-edit icon-large"></i>
        <span>Manager</span>
      </li>
      <li>
        <i class="icon-edit"></i>
        <a href="#">日記を作る</a>
      </li>
      <li>
        <i class="icon-edit"></i>
        <a href="#">総編集画面</a>
      </li>
    </ul>
  </div><!-- /carender -->
</div><!-- /side-mnenu -->

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
<td><%= link_to 'Show', account %></td>

app/views/blogs/index.html.erb
<div class="main">
  <% @blogs.each do |blog| %>
  <div id="blog_<%= blog.blog_id %>" class="blog">
    <h2><%= blog.blog_title %></h2>
    <div class="blog-detail">
     <%= nl2br(blog.blog_detail) %>
    </div>
    <ul class="blog-date">
      <li style="text-align: right;">
        <p></p>
      </li>
    </ul>
    <div class="blog-edit">
      <ul>
        <li style="text-align:right;margin-top:5px;">
          <a href="#" class="btn btn-primary btn-small">編集</a>
          <a href="#" class="btn btn-danger btn-small">削除</a>
        </li>
      </ul>
    </div>
  </div>
  <% end %>
  <a href="#" id="page-top" style="margin-top:20px;">
    <%= image_tag 'jump_logo.png', :class => 'roll' %>
  </a>
</div><!-- /main --><td></td>
<div class="side-menu">
  <div id="archive">
    <ul>
      <li class="title">
        <i class="icon-tag icon-large"></i>
        <span>Archive</span>
      </li>

    </ul>
  </div><!-- /archive -->
  <div id="manage-menu">
    <ul>
      <li class="title">
        <i class="icon-edit icon-large"></i>
        <span>Manager</span>
      </li>
      <li>
        <i class="icon-edit"></i>
        <a href="#">日記を作る</a>
      </li>
      <li>
        <i class="icon-edit"></i>
        <a href="#">総編集画面</a>
      </li>
    </ul>
  </div><!-- /carender -->
</div><!-- /side-mnenu -->

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blog:</strong>
  <%= @blog.blog_id %>
</p>

<p>
  <strong>Blog title:</strong>
  <%= @blog.blog_title %>
</p>

<p>
  <strong>Blog detail:</strong>
  <%= @blog.blog_detail %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniProject</title>
  <%= stylesheet_link_tag    "common.css", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "bootstrap/css/bootstrap.css" %>
  <%= stylesheet_link_tag "bootstrap/font-awesome/css/font-awesome.css" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrap">
  <div id="header">
    <div class="header-top" style="margin-bottom:3px;">
      <p>お手軽なブログシステム</p>
    </div>
    <%= image_tag 'top.png' %>
  </div>
    <div id="contents">
      <%= yield %>
    </div>
      <div id="footer"oote>
        <div class="fr-inner">
          © 2013-2013 hogehogehogehogehogehogehogehogehogehoge
        </div>
      </div><!-- /footer -->
</div>


</body>
</html>